- example/src/pages/TablePage.tsx
- src/Tables/index.ts
- src/Tables/molecules/TypeTable.tsx
- storybook/src/stories/Tables/TypeTable.stories.tsx
Including fixing an import and improving the functional that checks if all values in a table are checked.
> Small fixes and clean up

- example/package-lock.json
- example/src/index.tsx
- example/src/pages/LinePage.tsx
- src/LineUI/LineSet.tsx
- src/LineUI/LineUI.tsx
- src/LineUI/LineUIRTC.tsx
- src/LineUI/index.ts
- src/themes/light/custom.js
- storybook/package-lock.json
> Feature: Add Point feature and example to UI Kit

- example/src/App.tsx
- example/src/index.tsx
- example/src/pages/LinksPage.tsx
- example/src/pages/NotificationPage.tsx
- src/Alerts/atom/Notification.tsx
- src/Alerts/context/notificationContext.tsx
- src/Alerts/index.ts
- src/index.tsx
- storybook/.storybook/preview.js
- storybook/src/stories/Alerts/Notification.stories.tsx
This is a followup of the #28 PR that required implementation with Context
Currently having trouble initializing the context provider empty :(
> WIP -  Add Context Implementation of Notifications

- storybook/src/stories/Form/SmallInput.stories.tsx
- storybook/src/stories/Form/TextAreaField.stories.tsx
[Bugherd#22](https://www.bugherd.com/projects/216308/tasks/22)
[Quick] Re-organise the Form components in Storybook to make more sense.
Moving Small Input and TextAreaField to Input folders based on https://github.com/future-standard/scorer-ui-kit/pull/26#discussion_r560737778
> Quick Fix - Reorganize inputs in Form

- src/Filters/atoms/DateTimeBlock.tsx
- src/Filters/molecules/DatePicker.tsx
And also removed a chunk of old commented out code that was used when refactoring during development.
> Updated icons in DatePicker

- src/Global/MainMenu.tsx
prevent flex shrink on main menu.
> Bug: fix squished main menu on small screens

- src/Form/atoms/Input.tsx
- src/Form/molecules/TextField.tsx
Fix type definition of Text Field component to pass up the Input props properly
> Fix: text field to take action icon and callbacks

- src/Form/molecules/DurationSlider.tsx
- src/Form/molecules/PercentageSlider.tsx
Slider is not sending correct input value, it sends the previous.
Slider is not sending correct input because is sending last value updated in the middleman components.
Sorry for the inconvenience.
Screenshoots
> Hot Fix Slider value miss sends on Percentage and Duration component

- example/src/pages/LineVideoPage.tsx
- src/LineUI/LineSet.tsx
- src/LineUI/index.ts
Add area name property in lineset data to show it in the center of the line-ui area.
> Feature/line UI area name

- src/Form/atoms/Switch.tsx
Switch Component was not updating the position state and the inputRef checked value on  'checked' prop change.  This is fixed in Switch Component
> Switch Component: Update input and position value on 'checked'  prop change

- package-lock.json
- package.json
- src/index.tsx
- src/themes/dark.tsx
- src/themes/themeFallbackHelper.tsx
- storybook/.storybook/preview.js
enable use of partial dark theme even when not all defaults have been set.
> Feature: Add theme fallback helper

- .github/workflows/publish-beta.yml
- .github/workflows/publish.yml
https://github.com/future-standard/scorer-ui-kit/blob/0373025aa5d7b88fccda550395f52d14722779a6/package.json#L20 
pre publish only already makes it build on publish.
> Fix: Speed up the CI by not building 2 times during release

- src/Global/molecules/TopBar.tsx
- storybook/src/stories/Global/GlobalUI.stories.tsx
This PR closes #143 - Text goes over drawer
**Text goes over drawer**
I never test tables together with drawers, table headers have 99 z-index. Although the drawer was 100 z index, it was not working because of the constraint of the z index 9 of the parent.
Put drawer in a portal to remove the z-index:9 constraint of the Container element and now the z-index: 100 works correctly.
###Screenshoots
**Before**
**After**
> Fix text over drawer issue #23

- package.json
This is an issue created just to bump the branch with the tag
> Bump 1.5.4

- package.json
> Bump 1.5.5

- src/Form/molecules/CropTool.tsx
- src/Form/organisms/AvatarUploader.tsx
- storybook/src/stories/Form/FileManagement/AvatarUploader.stories.tsx
closes #170 - Remove button is hardcoded
closes #173 - Cross origin error on server image in Croptool
closes  #175 - Localization not working for buttonText, buttonTextReplace, uploaderCropText
I automatically formatted the file and some code will show changes but is just space fixes.
I notice when my VS Code updates I get new TS lint rules @-@
I deployed this branch to verify the replacements on a production environment - [Avatar Uploader](https://future-standard.github.io/scorer-ui-kit/storybook/?path=/story/form-file-management--avatar-uploader)
I was still not confident of the change so I decided to publish this branch as [1.6.1-beta.1 release](https://www.npmjs.com/package/scorer-ui-kit/v/1.6.1-beta.1) to try this fix on a reported project to verify it was working correctly.
Icon …
> Avatar Uploader fixes

- package.json
> Bump 1.6.1

- package-lock.json
- package.json
> Bump 1.7.1

- example/package-lock.json
- package-lock.json
- package.json
- src/Global/atoms/ContextItem.tsx
- src/Global/atoms/NavigationItem.tsx
- src/Global/index.ts
- src/Global/organisms/MainMenu.tsx
- storybook/package-lock.json
- storybook/package.json
- storybook/src/stories/Global/GlobalUI.stories.tsx
- storybook/src/stories/Global/MainMenu.stories.tsx
closes #171 - [Main Menu] External Link Indicator
I used the reference in the issue for design, please let me know if the sizes are correct or need to be adjusted.
> Add External Link to MainMenu

- package.json
> Bump 1.7.2

- package-lock.json
- package.json
Bump for release, mainly fixes for FilterBar, Label and Datepicker
> Bump 1.7.5

- src/Filters/molecules/DatePicker.tsx
- storybook/src/stories/Filters/molecules/DatePicker.stories.tsx
closes #229 
[Datepicker] 'From' label hard coded but needs to be definable. 
I have chosen the overriding option. Variables are descriptive but long.  I request your opinion on this, I could change it for title1 and tittle2 if you it's better.
I also updated the JSX parameters for the plugging perhaps I can do this every time I update a component and little by little it will become tidy.
JSX Before
JSX After
> Update for Date picker to receive text for titles

- storybook/src/stories/Filters/molecules/DatePicker.stories.tsx
Forgot to update the knob variable naming on previous PR
> Hot Update to Text in Updated Variables

- package-lock.json
- package.json
Bump for release, Datepicker and Menu fixes :D
> Bump version 1.7.6

- package-lock.json
- package.json
> Bump 1.7.7

- package-lock.json
- package.json
PR for release, this one has props update for Global UI
> Bump v1.7.8

- package-lock.json
- package.json
> Bump v1.7.9

- package-lock.json
- src/hooks/useMenu.ts
- storybook/src/stories/Global/GlobalUI.stories.tsx
Allows UI to default close on large screen when always pin is enabled
> Fix default menu open to do what it claims

- package-lock.json
- package.json
Bump for new version v1.7.10 
Features
GlobalUI and MainMenu new prop canAlwaysPin for big screens to pin too.
LineUIRTC and LineUIVideo have now showDirectionMark too to add direction action
> Bump release v1.7.10

- src/Filters/molecules/DatePicker.tsx
- src/Filters/molecules/DropdownDatePicker.tsx
- src/Filters/molecules/FilterDropdown.tsx
- storybook/src/stories/Filters/molecules/DatePicker.stories.tsx
- storybook/src/stories/Filters/organisms/FilterBar.stories.tsx
This PR addresses updates Dropdowns fixes
fixes #254 - DatepickerDropdown was not passing Text props 
fixes #255 - Worng using text as key
From - から
> Dropdowns update

- package-lock.json
- package.json
- src/Global/atoms/DrawerBottomMenu.tsx
- src/Global/index.ts
- src/Global/molecules/TopBar.tsx
- src/Global/molecules/UserMenu.tsx
- storybook/src/stories/Global/GlobalUI.stories.tsx
- storybook/src/stories/Global/TopBar.stories.tsx
Add Bottom menu in drawer
- Switch theme
- Language(modify)
Zeplin Design: https://app.zeplin.io/project/61f0fb56807607a416632e18/styleguide/components?coid=61f0fbbc052106a68cc358d4
Light theme(Top BAr):
Dark theme(Global UI):
> Dark Mode toggle

- package-lock.json
- package.json
Bump for release
Dropdown fixes
> Bump release v1.7.11

- example/src/pages/CustomUserDrawerPage.tsx
close #207 
- https://github.com/future-standard/scorer-ui-kit/issues/207
> Update example in Drawer to show search and user

- package-lock.json
- package.json
> Bump v1.17.12

- package-lock.json
- package.json
Release bump 1.17.13 for Datepicker Days and months localization
> Bump release/v1.7.13

- src/Form/atoms/SliderInput.tsx
closes #226
- #226 
Testing steps change default value in storybook
> Add slider defaults refresh with useEffect

- src/Filters/molecules/FiltersResults.tsx
closes #241
- #241
Testing steps select and clear items
> Add min height to filterbar results to prevent jump

- example/src/pages/LineRTCPage.tsx
Hot fix of a missing dependency that is failing in the deploy
> Update LineRTC missing dependecy

- package-lock.json
- package.json
> Bump for v1.7.14

- package-lock.json
- package.json
- Bump  for release for 1.7.15
> Bump por release v1.7.15

- README.md
This PR was purely made to have a commit tag with bump v1.7.15 after the deploy fix
> Bump 1.7.15-commit-forTag

- package-lock.json
- package.json
> Bump v1.7.16

- package-lock.json
- package.json
> Bump v1.7.17

- src/Misc/atoms/MediaBox.tsx
- src/Tables/atoms/TableRowThumbnail.tsx
- src/hooks/useMediaModal.tsx
- storybook/src/stories/Alerts/Modals/MediaModal.stories.tsx
- storybook/src/stories/Tables/atoms/TableRowThumbnail.stories.tsx
This are the changes created for Dark Mode branch in PR https://github.com/future-standard/scorer-ui-kit/pull/302
However cherry picking showed that there were other changes in the DarkMode Branch that were not reflected and was hard pin point.
I decided to checked out the 5 files from Dark Mode branch to make sure other PR's changes were also committed in this update.
All seems to be working right
> Thumbnail improvements from Darkmode branch

- example/package-lock.json
- package-lock.json
- package.json
- storybook/package-lock.json
- storybook/package.json
This updates the icons for UI Kit to have new version with new template.
Fixes  Filter Descending Icon 
Add's Dark Mode and LighMode Icon.
> Update Icons dependency to 2.0

- package-lock.json
- package.json
> Bump v1.7.18

- README.md
- dark_light_mode_usage.md
- package-lock.json
- package.json
- packages/ui-lib/README.md
- packages/ui-lib/package.json
Release for 2.0.0 with extra notes for Dark and light Theme
> Bump release v2.0.0

- src/Filters/atoms/DateTimeBlock.tsx
- src/Filters/molecules/DatePicker.tsx
- src/helpers/index.tsx
- This PR is for calendar component changes.
- In current component it not possible to remove current hh:mm value and enter new value. To fix this issue I have added functionality to add values directly in input box with the help of keyboard numbers.
- I have added validation when we put wrong values in time input box.
- When we add wrong value in input box it shows red colour as border to the input box.
- I have added blur event, if in input we add `0` or empty string so when we click outside of input box it will show `00` value in input box.
- Related Bugherd Requirement links
[Bugherd Issue](https://www.bugherd.com/projects/216134/tasks/132)
- Tested this work in TCC project.
> Fix calendar component date

- README.md
This is a quick update to better reflect the current thinking of usage and development between v1 and v2 branches.
> Update README.md to reflect v1 vs v2 thinking

- package.json
Bump for  release v1.7.27
Fixes
Percentage Slider: ShowTitleValue prop to hide value added.
UserDrawerMeta: on Menu Copy icon update to show visible on hover.
FilterDropdown: Will not hide the scrollbar.
> Bump v1.7.27

- package-lock.json
- package.json
Bump for v1.7.28 release
Update for Sliders to have centered option on extremities values
> Bump for v1.7.28 release

- package-lock.json
- package.json
> Bump for v1.7.29 release

- package-lock.json
- package.json
- packages/ui-lib/package.json
Bump for release 2.0.6
Updates from v1.7.30
> Bump for v2.0.6 release

- packages/example/src/index.tsx
Hotfix for storybook and examples page deployed.
> publish hotfix due examples index eslint error

- package-lock.json
- package.json
- packages/ui-lib/package.json
This is the PR for tagging the release v2.1.0 related to external css variables utilization
> Bump for release v2.1.0

- package-lock.json
- package.json
- packages/ui-lib/package.json
**Release v2.1.1**
**Note: Not intended as an upgrade to any projects currently using UI Kit V1.x versions.**
**Components**
SplitButton: A button with a Drop Down menu that can trigger an action when pressed.
**Fixes**
Updated Css variables in components that had a typo gray -> grey
Updated concept of Error to Warning and Warning -> Caution in Css variables
Theme toggle is working properly with the moon/sun interaction of Storybook
> Bump for release v2.1.1

- packages/example/src/theme/theme-variables.css
- packages/storybook/src/stories/Misc/molecules/Pagination.stories.tsx
- packages/storybook/src/theme/theme-variables.css
- packages/ui-lib/src/Form/atoms/SelectField.tsx
- packages/ui-lib/src/Misc/index.tsx
- packages/ui-lib/src/Misc/molecules/Pagination.tsx
- packages/ui-lib/src/helpers/index.tsx
- packages/ui-lib/src/index.tsx
- packages/ui-lib/theme/theme-variables.css
This is a Pagination component that has been used in many projects but we haven't integrate it to the UI Kit Yet. 
[Most resent design](https://app.zeplin.io/project/666a7d9f00bcfa44320386ed/screen/666a823b65115fce4f058ad3)
Run Storybook on local and Review Pagination story
Some interaction I have reviewed
**Correct Typing Values**
- Insert correct value and update by enter
- Insert correct value and update by click
- Insert correct value and leave
**Invalid Typing Value**
- Insert more than the value of pages and try to enter
- Insert more than the value of pages and try to click
- Insert 0 and try to enter
**Tab Interaction**
- Tab into arrows and move one page up by right arrow
- Tab into arrows and move one page down by left arrow
- Tab into arrows and move left but is page 1 and its …
> Pagination Component

- package-lock.json
- package.json
- packages/ui-lib/package.json
Release 2.1.2
Components
- Pagination : New component to control pages and items per page. 
Features
- Icons: Icons now support color variables as color not only predetermined colors like ‘mono’, ‘inverted’.
> Bump for release v2.1.2

- package-lock.json
- package.json
- packages/ui-lib/package.json
Release v2.2.0
**Components**
- Utility Header: Breadcrumbs and back button.
- FullWidthContentBlock and ContentLayout that use css variables for padding and width settings.
**Deprecated features and breaking changes**
- GlobalUIPage: New media query value ( 1400 -> 1536)  for large devices. Old layout can still be used by adding the `legacyLayout={true}`.
- Theme: Starting from this version, we will no longer use external CSS files for defining variables. This change allows for easier management of CSS and seamless updates of CSS variables using Styled Components' Global Styles. Each project can still maintain its custom CSS variables with this approach. Please review the update requirements in your Index file in the[ documentation](https://github.com/future-standard/scorer-ui-kit/blob/ma …
> Bump for release v2.2.0

- package-lock.json
- package.json
- packages/ui-lib/package.json
Small release 2.2.1 
Pagination: Fix of missing Pagination props selectId and itemsDefaultValue
> Bump for release v2.2.1

- packages/example/src/pages/TablePage.tsx
- packages/storybook/src/stories/Tables/atoms/TableRowThumbnail.stories.tsx
- packages/ui-lib/src/Tables/atoms/TableRowThumbnail.tsx
- packages/ui-lib/src/Tables/atoms/TypeTableRow.tsx
- packages/ui-lib/src/Tables/index.ts
- packages/ui-lib/src/index.tsx
Please provide the context of this PR.
Here are some questions to help you write this information.
This PR is a request to have the possibility to have a custom Modal by providing a way to override the onClick handler in the TableRowThumbnail component
Run Table -> Atoms ->  Thumbnail in  Storybook and Table Page in Examples 
**Storybook**
**Examples**
> TypeTable Thumbnail onclick option

- package-lock.json
- package.json
- packages/ui-lib/package.json
Bump for release v2.2.2
**Components:**
- SplytLayoutComponent: A layout component that enables a resizable split layout, which can be either horizontal or vertical. It also supports nested split layouts for more advanced configurations.
[Live example](https://future-standard.github.io/scorer-ui-kit/storybook/?path=/story/global-organisms--split-layout-nested)
[Further information](https://github.com/future-standard/scorer-ui-kit/pull/465)
- ButtonsBundle: A new component that provides a flexible column of buttons with flex-wrap, including buttons with icons. 
**Features:**
- BaseStyles: A Styled Component CSS that can be easily imported in to the project to ensure the base rules are correctly set.
- PageHeader: Style and functionality upgrade. The page title now supports different …
> Bump for release v2.2.2

- package-lock.json
- package.json
- packages/ui-lib/package.json
Release 2.2.3
**Fixes**
- PageHeader: Added missing IconColor prop to customize the color of the PageHeaderIcon
> Bump for release v2.2.3

- package-lock.json
- package.json
- packages/ui-lib/package.json
Hot fix for the SplitButton 
- SplitButton: Add z-index to dropdown to fix overlapping between split buttons.
[Live example](https://future-standard.github.io/scorer-ui-kit/#/table)
> Bump for release v2.2.4

- package-lock.json
- package.json
- packages/ui-lib/package.json
Bump for release:
DatePicker: Month Pagination hover color fixed.
> Bump for release v2.2.5

- package-lock.json
- package.json
- packages/ui-lib/package.json
Bump for release v2.3
**Components**
- Tooltip: A Textbox with Icon that is displayed when another component is hovered.  You must provide a reference to the hovered component using the `tooltipFor` prop.
- The background color of the tooltip can be customized using the `type` prop, limited to `ITooltipType` options: `warning`, `neutral`, `info`, and `success.`
- The position can be dynamic relative to the document or pre-set by the developer based on the `ITooltipPosition` type.
**Features**
- FilterButton: 
- Updated height to match new design pattern using css variable values.
- Added a `design` prop with options `default` and `basic`. The `basic` option removes borders and background, and will be the default for the `SortButton` (Dropdown button).
- Color Story: A [storybook …
> Bump for release v2.3

- package-lock.json
- package.json
- packages/ui-lib/package.json
Release 2.4
**Features**
- Font Page:  A new Storybook page showcasing the different font variations.
Example Index: The example project on the UI Kit main page has been updated with descriptions for each example. [Take a look] (https://future-standard.github.io/scorer-ui-kit)
**Fixes**
- Font Updates: 
- Added a new Lato font variant to improve design consistency.
- Set the `text-rendering` style value to `geometricPrecision` for improved text clarity.
- Updated GlobalUI to use a heavier font weight, matching the new Lato font files.
**Deprecated features and breaking changes**
To ensure consistency with the updated design, new Lato font files need to be manually added to your project when updating to this UI Kit version. The fonts can be downloaded from the [UI Kit Font …
> Bump for release v2.4

- package-lock.json
- package.json
- packages/ui-lib/package.json
Bump to fix bad tag release for 2.4
https://github.com/future-standard/scorer-ui-kit/pull/485
> Bump for release v2.4.0

- packages/storybook/src/stories/Filters/molecules/FilterDropdown.stories.tsx
- packages/storybook/src/stories/Filters/organisms/FilterBar.stories.tsx
- packages/ui-lib/src/Alerts/atom/AlertBar.tsx
- packages/ui-lib/src/Alerts/atom/Notification.tsx
- packages/ui-lib/src/CameraPanels/atoms/PanelMetaData.tsx
- packages/ui-lib/src/Filters/atoms/DateTimeBlock.tsx
- packages/ui-lib/src/Filters/atoms/FilterButton.tsx
- packages/ui-lib/src/Filters/atoms/FilterDropdownContainer.tsx
- packages/ui-lib/src/Filters/atoms/LoadingBox.tsx
- packages/ui-lib/src/Filters/molecules/DatePicker.tsx
- packages/ui-lib/src/Filters/molecules/FilterDropdown.tsx
- packages/ui-lib/src/Filters/molecules/FilterInputs.tsx
- packages/ui-lib/src/Filters/molecules/FilterLayout.tsx
- packages/ui-lib/src/Filters/molecules/FiltersResults.tsx
- packages/ui-lib/src/Filters/molecules/SortDropdown.tsx
- packages/ui-lib/src/Filters/organisms/FilterBar.tsx
- packages/ui-lib/src/Form/atoms/Checkbox.tsx
- packages/ui-lib/src/Form/atoms/FilterOption.tsx
- packages/ui-lib/src/Form/atoms/RadioButton.tsx
- packages/ui-lib/src/Misc/atoms/BasicSearchInput.tsx
- packages/ui-lib/src/theme/variables/Colors.ts
This PR continues the refactors to bring the UI Kit inline with the design library. It includes:
* Filter dropdowns now all use the special container component as standard.
* Filter dropdowns now have a nice new frosted glass style background.
* Updating Filter Buttons
* Updating filter dropdowns, containers and content styles.
* Updates color of checkboxes and radio buttons
* Updates various quick win fixes of legacy font-family variables.
> Filters refactors

- package-lock.json
Run npm audit to automatic fix critical, there were 7 now 4 more to go :D
> NPM security revision Part 1

- package-lock.json
cookie module version that had a low vulnerability fix
> cookie module version that had a low vulnerability fix

- package-lock.json
- package.json
- packages/ui-lib/package.json
Release 2.5
**Features**
- Buttons: Button sizes, including padding and text-sizes have been updated to new design and can be managed with css variables. Drop shadows are added as an optional prop.
- Filter dropdowns: New frosted glass style background.
- Checkbox: Updated Style using css variables.
- RadioButton: Updated Style using css variables.
- Icon button: Added a new loading option which switches the icon for the spinner
**Fixes**
- Animations: The easing types for animations were incorrectly set. The values and implementations have been corrected to ensure proper easing in and out effects.
**Deprecated features and breaking changes**
NPM dev dependencies have been updated to resolve critical security issues. These updates should not impact external projects, but if any errors …
> Bump for release v2.5.0

- package-lock.json
- package.json
- packages/ui-lib/package.json
Release v2.5.1
**Fixes**
- Pagination: The activePage prop value can now be updated dynamically by the developer. Previously, it functioned only as an initial value.
> Bump for release v2.5.1

- packages/ui-lib/src/Filters/atoms/FilterButton.tsx
- packages/ui-lib/src/Filters/atoms/FilterDropdownContainer.tsx
- packages/ui-lib/src/Form/atoms/Checkbox.tsx
- packages/ui-lib/src/Form/atoms/FilterOption.tsx
- packages/ui-lib/src/Form/atoms/RadioButton.tsx
- packages/ui-lib/src/theme/variables/Colors.ts
This fixes the following:
* Updates checkboxes and radio buttons to match the theme and using new CSS variables.
* Also updates the fake versions of these in the filter dropdowns.
* Removed unused CSS variables.
* Fixed small arrow icon hover color issue in the FilterButton
* Filter Dropdowns translucent background is a bit more opaque to better handle busy backgrounds
> Fixes: Checkbox, Radio and FilterButton color fixes

- package-lock.json
- package.json
- packages/ui-lib/package.json
Release v2.6.1
**Features**
- **Checkboxes and RadioButtons Components:** Updated CSS variables to reflect additional states. If your project overrides these components, please review all CSS variables starting with `--input-selection-control` and update them to the new `--input-toggle-` options. More information can be found in [PR #500.](https://github.com/future-standard/scorer-ui-kit/pull/500)
Fixes
- **FilterButton:** Arrow hover color issue fixed. Translucent background is a bit more opaque to improve visibility on busy backgrounds.
> Bump for release v2.6.1

- package-lock.json
- package.json
- packages/ui-lib/package.json
Release 2.6.2
**Features**
- TypeTable: Added row-level disable functionality for checkboxes. Now, if any row is disabled, the "Select All" checkbox will also be disabled. This ensures compatibility with previous versions and prevents unintended selection behavior for a more consistent usage across projects.
**Fixes**
- MainMenu: The ContextContainer now uses CSS to calculate its height, resolving issues where the height was previously cut off due to JavaScript calculations being applied at the wrong time.
> Bump for release v2.6.2

- package-lock.json
- package.json
- packages/ui-lib/package.json
**Fixes**
**- MainMenu:** Mobile version update for the ContextContainer. This fix adds mobileMenu prop for MainMenu and removes the loading state that was used to track when each NavigationItem had checked the height of its submenus.
> Bump for release v2.6.3

- package-lock.json
- package.json
- packages/ui-lib/package.json
Release 2.6.4
**Components**
- TopBarBadge:  Added functionality to show the user type in `TopBar` header for projects with guest access.: Allows passing a base color variable from theme vars and additional props to make the label a link using `linkHref` or React Router’s `linkTo`, with optional `linkText` on hover.
**Features**
DatePicker: A new optional `availableRange` prop of type `DateRange` has been added. This reduces the availability in the selection of dates, disabling dates that are out of range. Developers must ensure that the `initialInterval` is within the `availableRange`. If the `initialInterval` is out of range, the dates will be styled red to prompt users to update their selection.
> Bump for release v2.6.4

- package-lock.json
- package.json
- packages/ui-lib/package.json
**Release 2.6.5**
**Fixes**
- **SmallInput**: Quick fix to the unit label to stop it incorrectly line wrapping when text is in Japanese.
> Bump for release v2.6.5

- package-lock.json
- package.json
- packages/ui-lib/package.json
**Release 2.6.7**
**Features**
- **SelectField**:  Updated design with improvements. [View in Storybook](https://future-standard.github.io/scorer-ui-kit/storybook/?path=/story/form-atoms--select-field)
- Refactored to use new theme-based CSS variables.
- Added a `fieldState` prop to align with Input components.
- Slight height adjustment for better alignment.
- Introduced an optional icon at the start of the select field.
- Updated story to include a new variant with the icon.
Fixes
- **FilterBar:** Fixed issues with missing availableRange and `hasEmptyValue` props in `DropdownDatePicker`, which were preventing proper `FilterBar` configuration for DatePickers.
- **MediaBox**: Added a “No Media” placeholder. Fixed layout overflow issues with “Alt text.” The alt text is now conditionally …
> Bump for release v2.6.7

- package-lock.json
- packages/storybook/package.json
- packages/ui-lib/package.json
Icons repo update from v2.0.0 to v2.0.1
- Icons
- GroupCollapse
- GroupExpand
Review in Storybook Misc -> Icons
> Add Group Expand and Group Collapse Icons

- package-lock.json
- package.json
- packages/ui-lib/package.json
**Release 2.8.1**
Fixes
- Label: Fixed an issue where the required (blue dot) indicator was missing a space after the text.
- ToggleButton: Updated behavior so the colon now only displays if a `categoryLabel` value is provided.
> Bump for release 2.8.1

- package-lock.json
- package.json
- packages/ui-lib/package.json
Release 2.8.2
**Features**
- SplitLayout: Added a new `onSideAreaStateChange` callback that returns the sideAreaState value whenever it changes, enabling developers to track state updates. A `defaultCollapsed` prop has been added to allow the side area to start in a collapsed state when there is not a base value in the  localStorage.
> Bump for release 2.8.2

- .github/workflows/deploy.yml
- .github/workflows/lint.yml
- .github/workflows/publish-beta.yml
- .github/workflows/publish.yml
Hot fix for missing update from node 16 to 18 in workflow.
> Update node version for upgrade  Storibook8 in workflows

- package-lock.json
- package.json
- packages/ui-lib/package.json
Release 2.9.1
Features
- FilterBar: Updated the `DatePicker` and `DropdownDatePicker` components to include `Apply` and `Cancel` buttons. This allows users to select dates without immediately applying the value until they confirm. This update is backward compatible, meaning no changes are required for existing implementations.
[FilterBar Live version](https://future-standard.github.io/scorer-ui-kit/storybook/?path=/story/filters-organism--filter-bar)
If the previous behavior (where date selection was immediately applied) is preferred, set the `hasApply` prop to `false`. Learn more about this update and related changes in PR#541.(PR#541)[https://github.com/future-standard/scorer-ui-kit/pull/541]
- DurationSlider: Added a new `timeFormat` template string prop to DurationSlider. This allows …
> Bump for release 2.9.1

- package-lock.json
- package.json
- packages/ui-lib/package.json
**Features**  
- **GlobalUI:** The language attribute of the `<html>` element can now be updated by passing the `selectedLangAttribute` prop without requiring additional configuration.  
- If no value is provided, it will default to the user's browser language preference, ensuring the attribute is never unset.  
- This update also resolves issues such as unintended italics for Japanese text.
> Bump for release 2.9.2

- package-lock.json
- package.json
- packages/ui-lib/package.json
Release 2.10.0
**Features**
**Button:** New `text-only` and `outline` design. For the xsmall button variant change, the size of the icon has gone from 10 to 12 and the horizontal padding in the icon area has gone from 8 to 4. No breaking change with this update.  Updates can be review in storybook  in Button, ButtonWithIcon and ButtonWithLoading. [ButtonWithIcon in Storybook](https://future-standard.github.io/scorer-ui-kit/storybook/?path=/story/form-buttons--with-icon)
Fixes  and breaking changes
- Switch: toggle wasn’t updating correctly to the passed `check` prop value . Introduced a new prop called `defaultChecked` that defines the initial value and is primarily used in uncontrolled components. If the checked prop is used along with an onChange function, the component should handle …
> Bump for release 2.10.0
