future-standard/scorer-ui-kit

- example/src/pages/TablePage.tsx
- src/Tables/atoms/TypeTableCell.tsx
- src/Tables/molecules/TypeTable.tsx
- storybook/src/stories/Tables/TypeTable.stories.tsx
https://www.bugherd.com/projects/216308/tasks/9
Tables: Copy button often can't be reached because hover area is left. (see attachment)
Before this fix the problem seems to be that the copy button is absolute positioned -20px right and the icon overlaps in the area of the next table cell. 
I added conditional padding to header and cell depending of the config. This will keep the icon inside the cell.
I pushed the example config to have the copy icon in the created column.
> Fix cell hover for copy icon

- src/Form/atoms/Button.tsx
- src/Form/atoms/ButtonWithLoading.tsx
- src/Pages/atoms/PageTitle.tsx
[Bugherd25](https://www.bugherd.com/projects/216308/tasks/25)
For "Standard Button", "Disabled" works.
But for “With Icon” and “With Loading”, we still can push the button even “Disabled” is checked.
[Bugherd39](https://www.bugherd.com/projects/216308/tasks/39)
[Page Header] Allow setting a subarea title without needing a url. 
**Bugherd35 Disabled buttons**
:active was not working properly when the button was wrapping items.
:active:enable verifies that is not disabled
**Bugherd39**
I created a link and a non link where it doesn't have a url.
**Bugherd35 Disabled buttons video**
[InteractiveVideo](https://drive.google.com/file/d/14uYQJ5d-UFMS15jBTPUFUypfWs85lpCr/view?usp=sharing)
**Bugherd39 Page header**
> Fix  disabled background and SubArea Header

- src/Global/TopBar.tsx
- storybook/src/stories/Global/TopBar.stories.tsx
This is required on some Edge side projects where this isn't relevant. 
I originally wanted to do conditional hiding based on if `logoutLink` or `onLogout` were passed as props but as we set a default for onLogout I wasn't sure how to detect that as an empty function. If you can think of a better was to refactor this, happy to do that. Otherwise I've just gone with a simple boolean to show and hide.
> Prop to hide logout link in drawer

- example/src/pages/LinePage.tsx
- src/LineUI/LineUI.tsx
- src/LineUI/LineUIRTC.tsx
- src/LineUI/LineUIVideo.tsx
- src/LineUI/index.ts
Add boundryOffset in LineUI to prevent user to put the vertices of quadrangles/line near the border. This feature is required if image used in LineUI is undistorted.
> LineUI - Add boundaryOffset option

- src/themes/common.tsx
[Bugherd54](https://www.bugherd.com/projects/216308/tasks/54)
Better font-stack in theme [(See comments)
I don't think this has been a major issue at all but would be good to add the follow to the end of each font-family in theme/common fontFamily settings:
... Hiragino Sans, "ヒラギノ角ゴシック", Hiragino Kaku Gothic ProN, "ヒラギノ角ゴ ProN W3", Roboto, YuGothic, "游ゴシック", Meiryo, "メイリオ", sans-serif;
###Screenshoots
Miss added the mane of monorale to verify the fallback.
> Add fallback to fonts

- src/Global/TopBar.tsx
- storybook/src/stories/Global/TopBar.stories.tsx
[Bugherd55](https://www.bugherd.com/projects/216308/tasks/55)
[User Menu] Allow for current user to be hidden (use similar approach to how logout hide works)
I leave it at hasCurrentUser as true by default since it wasn't specified.
> Add CurrentUser as optional prop in top bar

- src/Alerts/atom/Modal.tsx
1.- Some designs have less than 300px height and current implementation doesn't allow to implement those.
2.- @atomworks mention that it would be great that the backdrop has blur.
Reviewed a couple of options fr the min-height with @atomworks and we decided just removing it will be better for now.
New Empty Modal
Previous templates, since content was bigger than 300px won't show any  difference
> Remove min-height and add blur to backdrop in modal

- src/Form/atoms/Label.tsx
- src/Form/molecules/DurationSlider.tsx
- src/Form/molecules/PercentageSlider.tsx
This is fix request from the FTI team
```
For other input component label  font-weight in ui-kit is 500, but in slider component doesn't have font-weight for the label. Is there any way so we can modify the styles of slider label? (Please check the attached snapshot)
```
I had not added the titles as Label component's the first time.
> Update Duration and Percentage Slider Titles to use Label component

- src/Form/atoms/Checkbox.tsx
- src/Tables/molecules/TypeTable.tsx
- src/themes/light/colors.js
- src/themes/light/styles.js
- storybook/src/stories/Tables/molecules/LoadingTable.stories.tsx
[Burherd#24](https://www.bugherd.com/projects/216308/tasks/24)
Bug: If a table has Select All but no entries then it is marked as checked. It should be uncheck and disabled or maybe just hidden.
I made the review of this on the Loading table of storybook.
Realized that checkbox had hover styling when disabled and modified a little the theme.
I felt a dejavu about it and I'm not sure if @atomworks  told me not to change that before hehehe..
Please review that the disabled check is working as designed.
AllChecked and enabled with empty loading
AllChecked and enabled when  background data loading
Empty AllCheckbox unchecked and disabled with loading
Data loading AllCheckbox checked disabled
Data loading Some checked, AllCheckbox not check disabled
> Fix checkAll in table and disable hovers in check component

- src/Form/molecules/DurationSlider.tsx
- storybook/src/stories/Form/DurationSlider.stories.tsx
Update the duration slider UI kit component to allow a mix of units
Previous implementation allowed to have custom marks and the slider does not take account of the unit but to update the top right label. I have updated to allow the user to control this tag and value. The rest of the component stays the same.
> Add example with mixed values for duration slider

- storybook/src/stories/Misc/Icons.stories.tsx
The Danger option was not available in the icons of storybook.
The specifics can be reviewed on issue #104
> Missing Danger color on icons storybook

- src/Global/index.ts
- src/Global/molecules/NotificationsHistory.tsx
- src/Global/molecules/TopBar.tsx
- src/Global/organisms/MobileNavbar.tsx
- src/Global/templates/GlobalUI.tsx
- src/Icons/StatusIcon.tsx
- src/Tabs/MobileTab.tsx
- src/index.tsx
- src/themes/light/colors.js
- storybook/src/stories/Global/GlobalUI.stories.tsx
- storybook/src/stories/Global/TopBar.stories.tsx
- storybook/src/stories/Misc/StatusIcon.stories.tsx
The requests of Issue #105 
Custom drawer with:
- An icon to the header.
- That icon can have a status color dot / counter.
- The drawer contents will be blank and allow for a custom component to be injected.
I created a StatusIcon to cover Dot and counter cases.
I notice in the design that the icon with status is smaller than the others, however the icon with the numbers looked kind of weird smaller than the counter so I left it same size, but let me know if it should be different.
**Status Icon**
**Desktop Version**
**Mobile Version**
> CustomDrawer in TopBar

- src/Form/atoms/ButtonWithIcon.tsx
- src/Form/molecules/CropTool.tsx
- src/Form/organisms/AvatarUploader.tsx
- storybook/src/stories/Form/FileManagement/AvatarUploader.stories.tsx
This is an update for  the Croptool
- Allow to pass a image
- Update hasCroptool
- Add props to pass button text to Croptools
closes #141
**Default img**
The Avatar uploader didn't have the option before.
**hasCrop update**
After the hasCrop was updated the logic with both was implemented this way, please confirm this is the expected.
basically if an image is provided and has crop will only edit that image in any other case the feature will allow the user to update the image and crop it if the crop feature is enabled.
Please confirm the logic of both together.
| initial button text  | defaultImg   | hasCrop   | button text after actions  |
|------------------|-------------|------------|------------------|
| Crop Image.        |     ✅              |  ✅               |  Crop Image         | …
> Avatar Upload feature iteration

- example/src/pages/TablePage.tsx
- src/Misc/atoms/MediaBox.tsx
- src/Tables/atoms/TableRowThumbnail.tsx
- src/hooks/index.ts
- src/hooks/useMediaModal.tsx
- src/hooks/useMediaQuery.ts
- src/hooks/useModal.tsx
- src/index.tsx
- storybook/src/stories/Alerts/Modals/MediaModal.stories.tsx
- storybook/src/stories/Tables/molecules/ActionsTable.stories.tsx
- storybook/src/stories/Tables/molecules/EditableTable.stories.tsx
- storybook/src/stories/Tables/molecules/TypeTable.stories.tsx
closes Bug #142 The video currently there is no limit to he height in modal probably we should limit it
closes Feature #155 - useMediaModal hook
- Updated MediaBox component to limit height and width space for modal but it's retro-compatible because this is only added if prop hasModalLimits is true
- Updated modal to have isModalOpen value available since it was mention that it would be helpful
- created useMediaModal hook to manage modal and MediaBox together with some strict values like width: auto, no padding and should always be close able.
- onError, onLoad props features for MediaBox
- Zoom in TableThumbnail only available if there is preview
currently this feature can be reviewed in the demo link.
https://future-standard.github.io/scorer-ui-kit/#/table
Video of interaction …
> Fix closeText in Modal over screen and improve MediaModal hook

- src/Form/atoms/SmallInput.tsx
- src/themes/light/styles.js
- storybook/src/stories/Form/Input/SmallInput.stories.tsx
closes #118 
[Storybook] In Form -> Input -> Small Input, error appears when State=Disabled. 
It was failing because disable focus was assigned but missing in theme.
Copied the values of disable normal.
No disable assignation value provided in storybook for the input value, although it doesn't break, the visual value would not appear correctly when disable "state" was provided. Also added the "not allowed" cursor when disable was true.
> Add missing disable values of theme of SmallInput

- src/Tables/molecules/TypeTableHeader.tsx
- src/Tables/organisms/TypeTable.tsx
- storybook/src/stories/Tables/molecules/LoadingTable.stories.tsx
This is a PR to fix the error on issue 144
closes #144  - Subheader of Grouping table goes over the message of no data 
The problem was that the Height Header was fixed to 50px (although because is display: table, height behaves as min-height).  Now with grouping is about 59px we need to contemplate this situation  and sometimes titles are long and have two lines which increments the height.
Now height is calculated and saved in a state and passed to the LoadingBox and the EmptyTableBox.
However notice that this is calculated on mount and re-calculated only onBreakpoint Change with the hook.
I added the hasHeaderGroups prop selection on Storybook but Storybook can't handle this well  because the Storybook wont remount the component when the hasHeaderGroups changes. 😞
I'm adding …
> Fix  Message of no data going over line of Grouping Header

- src/Icons/StatusIcon.tsx
Status icon is smaller than expected in real cases. 
There was a change request to have the same size regardless if it will have a Status Dot or not.
Before
After
> Update StatusIcon with or without status has same size

- src/Form/atoms/Label.tsx
This PR fixes #216 - Missing bottom margin in label
I made an update in Filter Bars to have Labels that could be right align but I missed a display:block property in the span that previously had, now is fixed and all is retro-compatible.
You can review this in Text Input component
Here you can see the Fix and how it's behaving currently.
> Fix missing display block in spans Label

- src/Global/atoms/NavigationItem.tsx
closes #224 - SubMenu missing after translation
There is a ref to the div of the submenu and it seems that it becomes 0 when it changes from one language to another.
I have added a condition to prevent to be updated to 0, but want to do beta test to verify.
> Fix submenu getting max-height 0 in language transition

- src/Tabs/atoms/Tab.tsx
- src/Tabs/index.ts
- src/index.tsx
Fix but in tab component where `onClick` is not passed down to tab component. 
Also exported Tabs context so we can make custom tab components that subscribe to the context.
Test Tab with onClick
> Fix: bug in tab component when onClick gets washed out by local onclick

- example/src/pages/LineRTCPage.tsx
- example/src/pages/LineVideoPage.tsx
- src/LineUI/LineUIRTC.tsx
- src/LineUI/LineUIVideo.tsx
- src/LineUI/LineUnit.tsx
This is an enhancement of previous PR (https://github.com/future-standard/scorer-ui-kit/pull/240) where we are adding direction mark on Line UI RTC and Line UI Video as well.
In Okinawa we have to show Direction mark on LineUI and LineUIRTC so this enhancement is required in this feature.
Zeplin design: https://app.zeplin.io/project/616e925cbde941134b0e7cbd/screen/61a4ad9c97d4ac134c19227d
image
Considerations on Implementation
The implementation is done for LineUIVideo and LineUIRTC components.
Reviewing/Testing steps
Follow the steps given at :
https://github.com/future-standard/scorer-ui-kit/tree/feature/line-ui-arrow-icon#readme
**Line WebRTC**
When project runs, Open http://localhost:3000/scorer-ui-kit#/linertc in browser you will see
**Line Video**
When project runs, Open …
> Add Direction Mark on LineUIRTC and LineUIVideo

- example/src/App.tsx
- example/src/pages/GlobalUIComp.tsx
- example/src/pages/GlobalUIPage.tsx
- example/src/pages/LinksPage.tsx
- src/Global/organisms/MainMenu.tsx
- src/hooks/useMenu.ts
In Support site one issue was reported to menu's Keep Open and Auto Hide state. In this requirement it was expected that Keep Open / Auto-Hide state must be preserve while we navigate to another page or reload the page.
Ref: https://www.bugherd.com/projects/281466/tasks/44
Follow the steps given at :
https://github.com/future-standard/scorer-ui-kit/
When project runs, Open http://localhost:3000/scorer-ui-kit#/globalUI in browser you will see
Click on KeepOpen  bottom and refresh menu.
> [Menus] preserve keep-open/auto-hide state in menu

- example/src/pages/TabsPage.tsx
- src/Tabs/atoms/Tab.tsx
In Support Site an issue was reported for selected and normal tab. When we clicks on tab name then horizontal alignment of selected tab and normal tab was not correct when selected language is Japanese. We have fixed this issue in this PR.
Ref: https://www.bugherd.com/projects/281466/tasks/42
Follow the steps given at :
https://github.com/future-standard/scorer-ui-kit/
When project runs, Open http://localhost:3000/scorer-ui-kit#/tabs in browser you will see
> [Tab component] horizontal alignment for tab name when language is Japanese

- src/Form/atoms/SelectField.tsx
- storybook/src/stories/Form/SelectField.stories.tsx
This is a bug reported in zenhub 
https://app.zenhub.com/workspaces/platform-team-61b9b760a8454700107d1a50/issues/future-standard/scorer-surveillance-dashboard/726
Select Dropdowns - Default value appearing as placeholder / disabled option
I think bug this is causing a bit of confusion in regards to usability. We just need to make sure that if it's a selected value that is shows the style correctly. At the moment the default values that are loaded are displayed how only the no selection / placeholder state should appear.
> Update SelectField to prevent default value having placeholder style

- src/Misc/index.tsx
- src/Misc/molecules/DebouncedSearcher.tsx
- src/index.tsx
- storybook/src/stories/Misc/molecules/DebouncedSearcher.stories.tsx
While I was working with the refactor of FilterBars one of the implementations of work around of filterbar was using a Debounce Searcher. The implemented refactor is not viable :( .. but this component might be useful for later so it's been added.
- Since the typed value is an internal state of this input 
I have added defaultValue as the external way to clear it or force it to change with an external value.
since is not "value" that is received from the parent it will help to prevent the infinite loop.
- This is not part of Filter Bars and is just for Searcher not part of other inputs
This is how The basic Search Looks
This is the Debounced searcher behaivour
> Debounce Searcher

- example/src/pages/LineRTCPage.tsx
- example/src/pages/LineVideoPage.tsx
- src/LineUI/LineUIRTC.tsx
closes #282 
- #282 
Added the video options and also tried to add to examples the case of stoping the looping of the video while opening a modal. This for Video and RTC
> Add video options to LineUIRTC with modal example

- src/Filters/molecules/FilterDropdown.tsx
- storybook/src/stories/Filters/molecules/FilterDropdown.stories.tsx
https://app.zenhub.com/workspaces/platform-team-61b9b760a8454700107d1a50/issues/future-standard/scorer-surveillance-dashboard/648
Filter dropdowns shouldn't paginate
At the moment the dropdown filter is limiting the choices to 5 but there are no pagination controls to see any others and it relys on knowing how to search for the remaining tags to show them.
The filter should instead allow for scrolling of this area internally after 5-7 entries are included.
https://drive.google.com/file/d/1l-Dzpm5ZuEh704DBpTFgRDqaG0Eka4eh/view?usp=sharing
> Filter dropdowns shouldn't paginate

- src/Form/molecules/ActionButtons.tsx
- storybook/src/stories/Tables/molecules/ActionsTable.stories.tsx
There was the request to have right align the action buttons on typetable.
I'm adding the capability of having alignment prop to generate this without loosing  previous compatibility.
> Add alignment options for Action buttons

- src/hooks/useMenu.ts
This PR for fixing a Bug in the previous PR  [preserve keep-open/auto-hide state in menu](https://github.com/future-standard/scorer-ui-kit/pull/296) 
Bug found if pass props canAlwaysPin = true then if screen resolution width more than 1400px and refresh the page then it shows Auto-Hide and auto close menu, it's not expected behavior.
Please follow the previous PR instructions. [LINK](https://github.com/future-standard/scorer-ui-kit/pull/296)
> Fix bug in preserve keep-open/auto-hide state in menu

- .github/workflows/deploy.yml
Currently the deploy is failing at github deploy
https://github.com/future-standard/scorer-ui-kit/runs/6703647712?check_suite_focus=true
I read online that this is a problem with cache 
https://github.community/t/error-cant-use-tar-xzf-extract-archive-file-return-code-2/254034
I have updated version in this branch with automatic deploy passed without problems
> Fix for cache error in main deploy

- src/Pages/atoms/PageTitle.tsx
- src/Pages/molecules/PageHeader.tsx
- src/hooks/useTitle.tsx
https://app.zenhub.com/workspaces/platform-team-61b9b760a8454700107d1a50/issues/future-standard/scorer-surveillance-dashboard/654
```
Page titles are stacking up!#654
As you can see from this screenshot of the back history, every time a new area is entered the page title is added to the start rather than replacing the previous area title.
```
I removed the state that is adding at the end the initial docTitle. 
I notice that when the title is empty it will add the delimiter then empty  `| `
When coming from another place the state is persisted so that is why is attached at the end.
Not sure which was the case scenario where this was necessary.
You can see in the after screen shot  how the "areaTitle" is attached at the end and it might not be ideal always (in surveillance project we use …
> Fix overlaping of titles and add hideAreaInDocTitle option

- src/Filters/molecules/FilterDropdown.tsx
Related to 648 request
https://app.zenhub.com/workspaces/platform-team-61b9b760a8454700107d1a50/issues/future-standard/scorer-surveillance-dashboard/648
```
At the moment the dropdown filter is limiting the choices to 5 but there are no pagination controls to see any others and it relys on knowing how to search for the remaining tags to show them.
The filter should instead allow for scrolling of this area internally after 5-7 entries are included.
```
It was visually not well the implementation of the height of the dropdowns, decided to update so when there is less choices it will grow with the choices yet continue to crop when there is more than 5 to show scrolling.
**Before**
**After**
> Fix height to big for a short list

- src/Filters/molecules/FilterInputs.tsx
- src/Filters/molecules/FiltersResults.tsx
- src/Filters/organisms/FilterBar.tsx
Filter results had alignment broken for non Japanese. 
Since some min-height was added in a different PR that I though my contribute to avoid this issue but there was still things to improve.
https://www.bugherd.com/projects/281466/tasks/27
Previous PR
https://github.com/future-standard/scorer-ui-kit/pull/288
Removed unnecessary margins and made consistency in FilterInputs
**Before**
**After**
> Fix aligment mismaches in Filter results

- src/Filters/molecules/FilterDropdown.tsx
- storybook/src/stories/Filters/molecules/FilterDropdown.stories.tsx
- storybook/src/stories/helpers/data_samples.tsx
- #347 
The design is available here: https://zpl.io/NwGM0zN
closes #347 
🙈  Noticed that the Search field and the empty results are 12px in the implementation and 14px in the design.
I don't remember why I re-wrote 12px on BasicInputSearch.
Do we leave it like is now or should I update this to 14px although we might find out the reason later..
or should I make this value variable/flexible for this case scenario?
> [Filter Dropdown] Empty State - Implementation

- src/Alerts/atom/AlertBar.tsx
- storybook/src/stories/Alerts/AlertBar.stories.tsx
closes #326
- #326
Adding the hiding prop will not affect behaviour since dismiss button was just not rendering the bar but actually this component was "cleared" in the developers component by their own state.
**Common usage**
> [AlertBar] Add hideCloseIcon prop to AlertBar Component

- src/Alerts/atom/Notification.tsx
- src/context/NotificationContext.tsx
- storybook/src/stories/Alerts/Notification.stories.tsx
- In `Notification` there is no option(prop) available to change that notification type "icon" on left and there is an requirement in the design.
- Added a prop: `icon` which can be used to change the type-icon.
- _Note: If `icon` prop is not specified then the component will follow default behavior that is the icon shown will depend on the type of notification._
- **When icon is not specified**
- **When icon is specified**
> Add icon prop to Notification Component

- example/src/pages/LinePage.tsx
- src/LineUI/LineSet.tsx
- src/LineUI/LineUI.tsx
- src/LineUI/LineUIRTC.tsx
- src/LineUI/LineUIVideo.tsx
- src/LineUI/LineUnit.tsx
This PR has updates for `LineUI` to provide support for customer requests. 
- Lines should be selectable on clicking them.
- Provide fix for overlapping of Line-label and `small-direction-arrow`
- Links of Bugherd issues
- [Selectable Lines](https://www.bugherd.com/projects/289019/tasks/159)
- [Overlapping issue](https://www.bugherd.com/projects/289019/tasks/157)
- For Selectable lines, Function binding is required with an parameter to `onLineClick` prop of LineUI which will be called when lines got clicked and `lineSetID` will be provided. We can use this **ID** to toggle `readOnly` and `showHandle` option of Lines
- For Overlapping issue, I kept previous implementation of line-label same, fix will only occur when we have `small-direction-arrow`.
- To test it just run the example pages …
> Feature/Line UI enhancements

- src/Tables/atoms/TableRowThumbnail.tsx
- src/hooks/useMediaModal.tsx
- In Tables, modal for row thumbnail has `min-height: 300` which is more than a QVGA(320 x 240) image due to which an extra space were seen in the bottom. This issue was reported by customer in below bugherd link.
- [Modal Extra space issue](https://www.bugherd.com/projects/289019/tasks/196) please check its attached thumbnail snapshot.
- I just reduced the `min-height` to `240px`.
- To verify and implement this, I used a QVGA image.
- **White space in height of QVGA image popup**
- **Fix**
> Fix/Table thumbnail modal min-height issue

- src/Filters/molecules/FilterDropdown.tsx
This PR consist a following bugfix:
All the filter dropdowns in the scorer-ui-kit, were having maximum 5 displayed options, among which last item was getting cropped as shown in below attached screenshot
**snapshot of ui having bug:**
So, as a fix of this bug, instead of increasing a max-height of OptionList from 162px to 170px, as per the suggested comment in the PR I have added a linear-gradient property to the option list if the options in the list are greater than 5 which looks proper as shown in below attached screenshot
**Here are some screenshots of the expected result.**
You can review this feature in this page
https://future-standard.github.io/scorer-ui-kit/storybook/?path=/story/filters-molecules--filter-dropdown
> Filter: Fix filter last item crop issue

- example/src/pages/LinePage.tsx
- example/src/pages/LineVideoPage.tsx
- src/LineUI/LineReducer.ts
- src/LineUI/LineSet.tsx
- src/LineUI/index.ts
This PR has following change in the LineUiVideo component:
-  In our recent component we don't have feasibility to fill color in the selected area created by a shape.
- Requirement is we should be able to specify for each shape it's fill color attributes including different transparency level for each independent of other.
[Zeplin Design for the Requirement](https://app.zeplin.io/project/6425995d21e4040182901a6c/screen/642599bf77d65979fe41598d)
- To achieve this we have added an optional color and opacity attribute to the **IPointSet** interface of LineUiVideo component.
- While creating a shape if user will pass color and opacity values in string then the respective shape will get filled with the passed color value with the transparency level given by opacity.
- If user will omit color …
> LineUiVideo -> Added color and opacity attribute to fill color in the shapes

- src/Global/index.ts
- src/Icons/StatusIcon.tsx
- storybook/src/stories/Global/GlobalUI.stories.tsx
- storybook/src/stories/Misc/StatusIcon.stories.tsx
This PR consist a following change in the ICustomDrawer interface-
1. In TopBar component, when the user showing a count of the notifications there might be possibility that count length gets increase to 4 or more as shown in below attached snap-
2. In order to get rid of such behaviour, we decided that if count exceeds **999** then we can show it as **999+** , as shown in below attached snap-
3. To achieve above, we need to concatenate a number with **+** sign, which will return a string 
4. But as **counter** in **ICustomDrawer** accepts number only it throws an error
5. Hence, we modified type of **counter** in **ICustomDrawer** as below:
**counter?: number | string**
Kindly go through below BH requirement link in order to get better clarity 
[BH …
> ICustomDrawer -> modified interface type of counter to accept string or number 

- src/Icons/StatusIcon.tsx
This PR consist following bugfix-
While building scorer-ui-kit, we came across an issue shown in attached snap below-
**Type 'number | undefined' is not assignable to type 'number'.**
> warning issue handled for maxCounter in case of undefined

- example/src/pages/LineRTCPage.tsx
- src/LineUI/LineUIRTC.tsx
This PR has following bugfixes in the LineUIRTC component:
1. On hovering over a line in LineUIRTC, a line doesn't show any click sensing border effect so a user can understand that, this is a line he is pointing to.
2. When selecting a line in LineUIRTC, by mouse click, it is difficult to select line by clicking exactly on line and also moving a line to different places.
**Considerations on Implementation**
1. Added a prop lineClickSensingBorder to give width to transparent border and default width of border is 65px, and
hasClickSensingBorder = true.
2. For selecting line, I have added on click functionality for arrows of line as well as name of line. Also I have added a showPointHandle & showMoveHandle prop to the lineset.
Here is screencast of the expected result. …
> WebRtc -> onClick  Line Selection and on hover border shadow

- packages/storybook/src/stories/Global/GlobalUI.stories.tsx
- packages/ui-lib/src/Global/index.ts
- packages/ui-lib/src/Global/organisms/MainMenu.tsx
- packages/ui-lib/src/Global/templates/GlobalUI.tsx
This PR has code for getting value true or false wether menu is open or closed. 
Here onMenuToggle callback is used to pass value to parent component. If menu is closed it will pass false other wise true,  
This feature is required in Platform renovation project to make organisation switch which is placed on top bar making its position abosulte near side menu. Problem arrived when user open menu or hover on menu the switch hide behind the menu. to overcome this problem code need callback to get menu open/closed value.
Here are some screenshots of the expected result.
**1. When menu is open its passed **true** value**
**2. When Menu is closed its passed false value**
> Add Callback and invocation for menu open close value - V2.

- src/Form/atoms/SliderInput.tsx
- src/Form/molecules/PercentageSlider.tsx
- storybook/src/stories/Form/Input/PercentageSlider.stories.tsx
This PR has following enhancement in the **PercentageSlider** component:
1. In our current component, we have Value title label showing at the top of the slider bar, as showing in the below attached snapshot.
2. There is a chances to make it's visibility show/hide based on the Boolean value passed by an user.
3. Hence, I have added a boolean prop named **showValueTitle** which will handle visibility of an element based on the value provided.
4. If true then label will be shown else it will be hidden.
> Percentage Slider -> Added prop to handle ValueTitle show/hide behaviour

- src/Global/atoms/UserDrawerMeta.tsx
- src/Global/index.ts
- storybook/src/stories/Global/TopBar.stories.tsx
This PR has following enhancement in the **UserDrawerMeta** component:
1. Copy Icon showing inside **UserDrawerMeta** component in the **TopBar** ui-kit's component is present based on value of the prop **hasCopyIcon**. If **hasCopyIcon** is true then Copy Icon will be present in the component, other it will be hidden.
2. Based on below BH requierment, it was required to show that copy icon only when user hover over the **UserDrawerMeta**, to achieve this, we have added one more prop named **hasHoverCopyIcon**.
3. When value of **hasHoverCopyIcon** is true then the copy icon will be visible only when user hover over the **UserDrawerMeta**. If it is false, then the copy icon will be visible always irrespective of onHover event.
[BH …
> Copy Icon in userDrawerMeta component handled conditionally

- src/Filters/molecules/FilterDropdown.tsx
This PR has following bugfix in the FilterDropdown component:
- The virtical scrollbar for this dropdown list is too narrow.  So it is very difficult to operate on it. Refer screenshot attached below
[BH Requirement](https://www.bugherd.com/projects/263632/tasks/461)
**Considerations on Implementation**
- Removed below styling applied on the scrollbar-
**/* Firefox supports the scrollbar-width property */
scrollbar-width: thin;
/* Customize the scrollbar width for Chrome and Safari */
::-webkit-scrollbar {
width: 2px;
}
::-webkit-scrollbar-thumb {
border-radius: 10px;
background: #44444499;
}**
Here is screenshot of the expected result.
> FilterDropdown -> verticle scrollbar styling changed

- src/Form/atoms/SliderInput.tsx
- src/Form/molecules/PercentageSlider.tsx
- storybook/src/stories/Form/Input/PercentageSlider.stories.tsx
- storybook/src/stories/Form/Input/SliderInput.stories.tsx
This PR has following enhancement in the PercentageSlider component:
- In our current component, it was noticed in the demo by @h2suzuki san that the alignment of the min (0%) and max(100%) values are not proper as shown in below attached snapshot,
- So, I have aligned  min (0%) and max(100%) values as shown in the below attached snapshot,
> Percentage slider -> Aligned min/max dividers

- src/Filters/atoms/DateTimeBlock.tsx
- src/Filters/molecules/FiltersResults.tsx
- storybook/src/stories/Filters/organisms/FilterBar.stories.tsx
This PR is an update request of the Issue 
https://github.com/future-standard/scorer-ui-kit/issues/439
Right now midnight is not correctly reflected in the text of filter results input
24:00 is shown as 23:59 the request is to show the next day at 00:00
The format sent by the user might influence the output but that is related to date-fns and should be handled by the Developer using UI Kit
yyyy-MM-dd HH:MM will show 2024-03-14 00:03 - 2024-03-15 00:03
yyyy-MM-dd HH:mm while using minutes lowercase will show 2024-03-14 00:01 - 2024-03-15 00:00
Out of the scope of this PR is to fix the DatePicker wrong Dates related to 24 hours 
Currently when the user updates the date to 24:00 the value is received as 23:00 by the developer.
This will be fix in a different PR.
Run storybook in local
On …
> Update FilterResults to transform midnight input into next day

- example/src/pages/LinePage.tsx
- example/src/pages/Login.tsx
- example/src/pages/TabsPage.tsx
- storybook/src/stories/Alerts/Modals/LoginModalExample.tsx
- storybook/src/stories/Form/Input/Input.stories.tsx
- storybook/src/stories/Form/Input/SmallInput.stories.tsx
- storybook/src/stories/Form/Input/TextAreaField.stories.tsx
There was a problem on a project that showed warnings in chrome, when reported it was mention that the same error was in our code. The solution was to update the missing parameters of id and htmlfor in labels. 
This PR corrects this problem in the examples to avoid the warnings and avoid confusion.
Two occurrences are shown because missing id on small input and one that is always present from Storybook code
After the update there is stilll the Storybook code shown but not in the small input
Testing just check the components in Example and Storybook
> Update missing htmlfor, name, id missing in examples

- src/Filters/atoms/DateTimeBlock.tsx
- src/Filters/molecules/DatePicker.tsx
- src/helpers/index.tsx
This PR is a refactor of the DateTimeBlock feature of the Date Picker.
The expected improvements are:
- 24 hours fix,  the issue with  the current code base is that allows to have non zero minutes and the callback will return 23 hours. (24:04 -> 23:04)
- Updated the logic in  Date range validation that colors the Time with red for edge cases
- Rolling minutes (Minutes can increment hour when pressing keyup after 59,  or decrement when pressing key down after 00 unless clock is at 00:00 or 23:59)
In this refactor I used current main 2.0 as base,  I will list things that were removed from 1.0 for easier review but mostly removed the logic added from this PR [#392](https://github.com/future-standard/scorer-ui-kit/pull/392)
- Consolidated back Input for Date and Time since the difference …
> Fixes for DatePicker -  DateTimeBlock

- package-lock.json
- package.json
Bump for release 1.7.30
Fixes
- Datepicker: 23-24 hours fix with rolling minutes to the next or previous hour when required.
- HTMLfor missing examples
> Bump for v1.7.30 release

- packages/ui-lib/src/Form/atoms/FilterOption.tsx
- packages/ui-lib/src/Form/atoms/IconButton.tsx
- packages/ui-lib/src/Form/molecules/CropTool.tsx
- packages/ui-lib/src/Global/atoms/ContextItem.tsx
- packages/ui-lib/src/Icons/Icon.tsx
- packages/ui-lib/src/Icons/index.d.ts
- packages/ui-lib/src/Misc/atoms/BasicSearchInput.tsx
- packages/ui-lib/src/Misc/atoms/Tag.tsx
- packages/ui-lib/src/Modals/Modal.tsx
- packages/ui-lib/src/Tabs/atoms/MobileTab.tsx
This updates icon color selections to use CSS variables instead of the older json based system. The older JSON stays in place for now so not to break project integration, however a deprecation warning has been added to the console.
From here, the color reference is the name of the color variable without the `--` prefix. For example, `grey-9` or `primary-6`.
- Updates all references done via `theme.colors.icons` to `var(--example-12)` css vars.
- Updates the `ISvgIcons` type so the color is simply a `string`.
- Added a deprecation `console.warn` message for use of the old references.
This work is required for the upcoming layouts feature but is being sent seperately for ease of review.
> Icon color selection switched to CSS Variables

- packages/example/src/style.ts
- packages/ui-lib/src/Global/atoms/Layout.tsx
- packages/ui-lib/src/theme/ThemeHelpers.ts
- packages/ui-lib/src/theme/ThemeVariables.ts
Removes the flex from the `#root` selector which was breaking the layout of some examples and stories. It was added as part of a fix to the layouts not spanning the full height of the container and backgrounds being cut off when scrolling, however it seems that this flex on #root was redundant.
> Fix to layout breaks on examples and stories.

- packages/storybook/src/stories/Pages/PageHeader.stories.tsx
- packages/ui-lib/src/Pages/molecules/PageHeader.tsx
Hot fix of the missed  colorIcon prop in Page header
Run storybook Page Header and select different colors for iconColor
> Add missing colorIcon in PageHeader

- packages/example/src/pages/TablePage.tsx
- packages/ui-lib/src/Form/molecules/SplitButton.tsx
Bug Fix for SplitButton
When the SplitButton is around other split buttons the dropdowns overlap because the z-index is the same.
I have updated it so if it's open z-index will be 100 which is the same that other dropdowns in this library 
Run locally the TablePage in Examples project
> Fix overlapping SplitButton when using it on table

- packages/ui-lib/src/Filters/molecules/DatePicker.tsx
Month pagination in Datepicker had a hover color of white that works great in Darkmode but will not be visible in Light Mode. 
Fixed updating colors.
I have used colors that look more more contrasting but had no design to match up.
Review on Storybook running on local
Filters -> Molecules -> Datepicker
> Datepicker Month pagination hover color fix

- packages/example/src/components/StatusComponent.tsx
- packages/example/src/pages/TablePage.tsx
- packages/storybook/src/stories/Alerts/Tooltip.stories.tsx
- packages/ui-lib/src/Alerts/atom/Tooltip.tsx
- packages/ui-lib/src/theme/variables/Colors.ts
Exploring using `ref` based component interaction in place of `id` based. This updates  the main component and the example use in both the Storybook text hover code and the Example's table's status dots.
I experience one of the things you were warning about with the use of refs in the context such as the table example. I believe the solution I came to is suitable.
If you choose not to merge this, please feel free to close it (with some attention to the below). Thank you!
---
_As it was a minor update, I've pushed a commit to the main PR for those color updates. So hopefully the changes here will merge across with no impact or can be forgotten if this is rejected._
~~There is also a color update which should be updated in the `feature/tooltips` branch, even if this PR is rejected. It's …
> Feature/tooltips (Ref based)

- packages/storybook/src/stories/Misc/molecules/Pagination.stories.tsx
- packages/ui-lib/src/Misc/molecules/Pagination.tsx
This is a fix request for the Pagination Component that was not updating value from property.
The specific scenario requested is:
```
Suppose if user previously choose 10 items per page, and then goes to last page and thereafter he changes page size again to 20, in that case total pages count decreases but the current selected page does not change as shown in snapshot below and its false to show such case in UI so I think activePage prop is not bind with its passed value due to which we get this situation.
```
I have updated the code to update  pageValue if activePage is updated.
Page Value is an temporary state to check the validity of input of the user.
activePage is been validated under the user input standards.
Updated default value of total pages from 199 to 1, seems like a more …
> Pagination activePage prop not updating value

- packages/example/src/pages/FormPage.tsx
- packages/storybook/src/stories/Filters/molecules/FilterDropdown.stories.tsx
- packages/storybook/src/stories/Filters/organisms/FilterBar.stories.tsx
- packages/storybook/src/stories/Form/Input/Input.stories.tsx
- packages/storybook/src/stories/Form/Input/PasswordInput.stories.tsx
- packages/storybook/src/stories/Form/Input/SmallInput.stories.tsx
- packages/storybook/src/stories/Form/Input/TextAreaField.stories.tsx
- packages/ui-lib/src/Form/atoms/Input.tsx
- packages/ui-lib/src/Form/atoms/Label.tsx
- packages/ui-lib/src/Form/atoms/SmallInput.tsx
- packages/ui-lib/src/Form/atoms/TextArea.tsx
- packages/ui-lib/src/Form/molecules/PasswordField.tsx
- packages/ui-lib/src/Form/molecules/TextAreaField.tsx
- packages/ui-lib/src/Form/molecules/TextField.tsx
- packages/ui-lib/src/theme/ThemeVariables.ts
- packages/ui-lib/src/theme/variables/Colors.ts
This PR contains two main changes:
1. Refactor inputs to match designs and use the new CSS variables.
2. Introduced a new blue dot 🔵 next to field labels to signify they are required fields.
This refactors some the common form fields that have had design tweaks and seeks to replace legacy theming with the new CSS variables.
This is similar to previous refactors. It updates sizes and colors, introducing the usage of new CSS variables and removing the old theme integrations.
`Input`, `InputField`, `TextArea`, `TextAreaField` and `PasswordField` have a new `showFeedback?: boolean` prop which if not set will default to `false`. This is because the feedback messages are no often used in designs however this feature is planned to be iterated, in which case the new feature will use the same …
> Form component refactors

- packages/example/src/components/ExamplesFilename.tsx
- packages/example/src/pages/CustomAlertsPage.tsx
- packages/example/src/pages/CustomUserDrawerPage.tsx
- packages/example/src/pages/FormPage.tsx
- packages/example/src/pages/GlobalUIPage.tsx
- packages/example/src/pages/Index.tsx
- packages/example/src/pages/Layouts.tsx
- packages/example/src/pages/LinePage.tsx
- packages/example/src/pages/LineRTCPage.tsx
- packages/example/src/pages/LineVideoPage.tsx
- packages/example/src/pages/Login.tsx
- packages/example/src/pages/PTZPage.tsx
- packages/example/src/pages/SplitLayout.tsx
- packages/example/src/pages/TablePage.tsx
- packages/example/src/pages/TabsPage.tsx
This feature adds two minor but useful improvements to Examples.
1. The index has a label on now with the filename of the source code it uses.
2. The individual examples also have a small label in the bottom center for this.
3. Next to this label in examples is a small home button to get back to the top level.
This is intended to help reduce friction when sharing examples and helping engineeers find the code to reference.
There is also a few minor changes to color and border on the index to help is be more readable in dark mode.
> Added Filename and a home button to examples

- package-lock.json
- package.json
- packages/ui-lib/package.json
Release v2.60
**Features**
- Page Examples: The listed projects on the homepage now include a label displaying the source document name. Additionally, each example page features a "Home" button at the bottom center, allowing users to return to the main page.
- Input, InputField, TextArea, TextAreaField, and PasswordField Components: These components have been reworked to align with new design. Updates include:
- Updated sizes and colors, incorporating new CSS variables.
- A blue dot is now displayed by default on the label when the required prop is passed. This required prop indicates that the field is required, while fieldState='required' is used when a form has been submitted but the field is left empty. (If a project does not use the blue dot for required fields, you can override the …
> Bump for release v2.6.0

- packages/storybook/src/stories/Tables/molecules/LoadingTable.stories.tsx
- packages/ui-lib/src/Tables/atoms/TypeTableRow.tsx
- packages/ui-lib/src/Tables/index.ts
- packages/ui-lib/src/Tables/molecules/TypeTableHeader.tsx
- packages/ui-lib/src/Tables/organisms/TypeTable.tsx
This is an update request for TypeTable component.
Currently the checkboxes in the rows can't be disabled by developer side.
This update will allow to disable them while still checking the states for the allChecked Checkbox
I decided to use the logic if at lease one checkbox in rows is disable the checkAll/ unCheckAll will be disable too.
Attaching the reasoning of this logic
I updated the example toggles to use previous as base prevent useEffect forever cycle when updating.
Test on storybook `Tables -> Molecules -> LoadingTable`  local using disable 1st checkbox
> Add disableCheckbox option to rows

- packages/ui-lib/src/Global/atoms/NavigationItem.tsx
In the main menu, when sub-menu items were being added or removed conditionally the useEffect that was calculating the height of the container to animated the closing was not firing. This led to the container being the wrong height and rendering incorrectly.
I've removed this max-height approach and replaced it with a CSS only method that will render the open height natively in the browser, meaning it is scalable and does not require and recalculation in our code to achieve.
This implementation leaves in some code that appears to be redundant but would take additional fix and review time that is riskier to deploy for this hotfix, due to delivery pressures on the projects relied on. However, I will follow up immediately on these changes in PR #505.
Note: This breaks the layout of the …
> Hotfix: Main Menu - Sub Menus wrong height if contents was changed after initialisation

- packages/ui-lib/src/Global/atoms/NavigationItem.tsx
- packages/ui-lib/src/Global/organisms/MainMenu.tsx
- packages/ui-lib/src/Global/organisms/MobileMenu.tsx
This completes the work from the hotfix of PR #504. It includes:
- Fixes to the mobile menu heights, removing the previous minHeight implementation and using a new `mobileMenu` prop to define the difference.
- Removes the `loading` state that was used to track when each `NavigationItem` had checked the height of its submenus. As it didn't appear to be used for anything else practical outside of these, it's been removed along with the ready callback which was part of this check.
- This has also been removed from the `mobileMenu`
Once this has been reviewed and you're happy with the menu functionality, we can deploy this. There is rush though as with the hotfix version of this.
> Submenu height fix.

- packages/storybook/src/stories/Filters/molecules/DatePicker.stories.tsx
- packages/ui-lib/src/Filters/index.ts
- packages/ui-lib/src/Filters/molecules/DatePicker.tsx
- packages/ui-lib/src/index.tsx
This PR introduces the ability to restrict the selectable date range in the Date Picker component as requested.
```
The date picker needs two additional props:
- Upper selectable date limit
- Lower selectable date limit
`In the DatePicker UI this will restrict` the selectable date range with dates outside that range being un-selectable. This feature is only required for date and not for time ranges.
As a stretch goal, if there is time please also consider adding the following options:
- Only future dates selectable (today and onward)
*This would be for use cases such as scheduling a task.*
- Only past dates selectable (today and past)
*The use case for this is commonly viewing data logs.*
```
To enable this functionality, a new optional prop, `availableRange`, of type `DateRange`, has …
> Datepicker  Date Range availability

- packages/ui-lib/src/Form/atoms/SmallInput.tsx
Quick fix to the unit label in `SmallInput` to stop it incorrectly line wrapping when in Japanese. Simple css fix.
Before: 
After:
> Fixed incorrect wrapping of jp in SmallInput's unit label

- packages/storybook/src/stories/Global/molecules/UtilityHeader.stories.tsx
- packages/ui-lib/src/Layouts/index.ts
- packages/ui-lib/src/Layouts/molecules/UtilityHeader.tsx
This simply adds the home icon to the top level of the breadcrumb. It is set to on by default as the top level is usually intended to be the home reference but this can be optionally switched off if the project chooses to treat this differently. This is done with the `showHomeIcon?: boolean` prop. 
At the moment no projects are known to be using this feature so this change isn't deemed to be breaking or disruptive. The first project this has been requested for will require this icon, though it is not critical.
New home icon can be seen here:
> Breadcrumbs have Home icon added to top level

- package-lock.json
- package.json
- packages/ui-lib/package.json
Release 2.6.6
**Components**
- **ToggleButton:** A new component that alternates the icon and text of the FilterButton. It can be used to toggle between two states, such as [switching between two layout types.](https://future-standard.github.io/scorer-ui-kit/storybook/?path=/story/filters-atoms--toggle-button)
**Features**
- **UtilityHeader:** Added a home icon to the top level of the breadcrumb. The icon can be removed by setting the showHomeIcon prop to false.
> Bump for release v2.6.6

- packages/storybook/src/stories/Filters/organisms/FilterBar.stories.tsx
- packages/ui-lib/src/Filters/molecules/DropdownDatePicker.tsx
This is fix of a missing prop `availableRange` prop in `DropdownDatePicker` that prevents `FilterBar` to pass DatePickers configuration correctly.
Reported Error
`
I have used the availableRange prop within the datePickersConfig of the FilterBar component. However, it doesn't seem to have any effect on the DatePicker within the FilterBar component, even though it works perfectly with the standalone DatePicker component.
`
- Added also missing hasEmptyValue.
- Added DateRanges to FilterBar Story, Unfortunately for the way the Language is handle in stories the object of knobs can not be used directly without losing the ability to switch Languages. I think this is something that will also be improve with by making a substitution to Controls.
I did a local test to verify the Out of range …
> Fix for missing Date Ranges in filterBar

- packages/storybook/src/stories/Form/SelectField.stories.tsx
- packages/ui-lib/src/Form/atoms/SelectField.tsx
- packages/ui-lib/src/Form/atoms/SmallInput.tsx
- packages/ui-lib/src/Icons/Icon.tsx
- packages/ui-lib/src/Misc/atoms/BasicSearchInput.tsx
- packages/ui-lib/src/theme/ThemeVariables.ts
- packages/ui-lib/src/theme/variables/Colors.ts
The Select has been refactored to remove the old theming, link it to the new CSS theme and also add a new icon feature. 
- Refactored to new theme code
- Added `fieldState` to match `input`
- Slight adjustment in height
- Added new optional icon to start of select
- Updated story with new variant for the icon.
As there is a new variable for the input compact height, the `BasicSearchInput` has also been updated to use this.
This update should not create any breaking changes. If the size adjustment of the select field causes problems in existing projects, it can be fixed a custom CSS override on the `--input-height` and `--input-compact-height` variables.
Preview:
https://github.com/user-attachments/assets/f96d4330-c0b6-405e-8b79-7e800241db0a
_Note, there is a bug in the preview with icon …
> Select component - Refactor and icon

- packages/storybook/src/stories/Indicators/Spinner.stories.tsx
- packages/ui-lib/src/Form/atoms/Label.tsx
- packages/ui-lib/src/Form/atoms/SplitButtonOption.tsx
- packages/ui-lib/src/Form/atoms/Switch.tsx
- packages/ui-lib/src/Indicators/Spinner.tsx
- packages/ui-lib/src/theme/ThemeVariables.ts
- packages/ui-lib/src/theme/variables/Colors.ts
This PR refactors the switch to match new designs, refactor out the legacy theme code and make some general quality improvements to the interactions. As part of this, the Spinner component has also got a slight upgrade with some custom components that mean it will work correctly if the switch is resized.
Here are a list of the changes made to the `Switch`:
- The theme has been replaced to match the new style and fully integrate with the newly added CSS variables.
- Because of this, now the switches are fully light and dark mode compatible.
- It has size variables in CSS that mean it can be resized if needed. While thinking forward, this also means that for legacy projects, the previous size of the switch can be restored.
- The label now uses the Label component to ensure that it is kept …
> Switch Update and Refactor (with changes to Label and Spinner)

- packages/storybook/src/stories/Form/Input/RadioButton.stories.tsx
- packages/ui-lib/src/Form/atoms/Label.tsx
- packages/ui-lib/src/Form/atoms/SelectField.tsx
- packages/ui-lib/src/Form/index.ts
- packages/ui-lib/src/Misc/molecules/Pagination.tsx
This fix was primarily to fix issue #525, however it also includes related fixes and refactoring to the `Label` component to bring that more in line with the flex approach we are taking more now. This in turn will make it more easily used among other components which should but don't yet use it.
The main change to be aware of is the addition of the new `direction` prop which will be used to handle where the label is in relation to the field is it wrapping.
`column` is the default. It is used when the label is above, such as for text inputs.
`row` is used when the label should be to the left of the input. For example, the pagination controls do this.
`row-reverse` is used when the text goes after the input, such as in the case of radio buttons.
The following two props have been marked for …
> Bugfix/525 Pagination fix with Label refactor

- packages/ui-lib/src/Filters/FilterTypes.ts
- packages/ui-lib/src/Filters/atoms/FilterButton.tsx
- packages/ui-lib/src/Filters/atoms/FilterDropHandler.tsx
- packages/ui-lib/src/Filters/atoms/ToggleButton.tsx
- packages/ui-lib/src/Filters/index.ts
- packages/ui-lib/src/Filters/molecules/FilterDropdown.tsx
- packages/ui-lib/src/Filters/molecules/SortDropdown.tsx
There was an error introduction when `FilterButtonDesign` type was added on the Filters index in the refactor of SortDropdown. https://github.com/future-standard/scorer-ui-kit/issues/511
`
Circular dependency: src/Filters/index.ts -> src/Filters/molecules/SortDropdown.tsx -> src/Filters/index.ts
Circular dependency: src/Filters/index.ts -> src/Filters/molecules/SortDropdown.tsx -> src/Filters/index.ts
`
The circular dependency was fixed by moving the type from index to the Filter types files, all files that use `FilterButtonDesign` type were updated.
Due the nature of the error, this can only be seen on the logs for the hot reload of ui-lib package.
Run the project on local and review the circular dependency error is not present.
> Fix circular dependency error for  FilterButtonDesign type

- packages/storybook/src/stories/Filters/molecules/DatePicker.stories.tsx
- packages/storybook/src/stories/Filters/organisms/FilterBar.stories.tsx
- packages/storybook/src/stories/helpers/datePicker_sample.ts
- packages/ui-lib/src/Filters/molecules/DatePicker.tsx
- packages/ui-lib/src/Filters/molecules/DropdownDatePicker.tsx
This is a new Feature request for the Datepicker
`
A new date picker feature where a list of dates or date ranges can be provided which will then place a dot on the date picker to signify, for example, that there is content available to view within that range.
`
Moved examples data to new data helper file for DatePicker examples.
I decided to add go with the dates array for content.
Test in Storybook
Filters -> Molecules -> DatePicker
Filters -> Organism -> FilterBar
> Datepicker Dot Markers

- packages/ui-lib/src/Form/atoms/Label.tsx
- packages/ui-lib/src/Misc/molecules/Pagination.tsx
This fixes the conflict that arose with `Switch` after it was merged along with additional `Label` refactors. There are two parts.
1. Made the `direction` prop optional, as originally intended.
2. Removed the old `sameRow` implementation from `Pagination` and updated it to the new `direction` prop.
> Post-Merge Label and Switch conflict fix

- package-lock.json
- package.json
- packages/ui-lib/package.json
Release 2.6.7
**Features**
- **DatePicker**: Added a new `contentDays` prop. Passing an array to this prop displays a dot on the days with available content. [Live view](https://future-standard.github.io/scorer-ui-kit/storybook/?path=/story/filters-molecules--date-picker)
- **Label**:
- Updated to support theme-based CSS.
- Added an optional `direction` prop to control the label's position relative to the field it wraps:
- `column` (default): Places the label above the field (e.g., for text inputs).
- ` row`: Positions the label to the left of the field (e.g., pagination controls).
- ` row-reverse`: Place the label to the right of the field (e.g., radio buttons).
- **Switch**:
- Updated to match the new theme style with full integration of CSS variables, making it fully compatible with …
> Bump for release v2.7.0

- packages/example/src/pages/Layouts.tsx
- packages/storybook/src/stories/Global/GlobalUI.stories.tsx
- packages/storybook/src/stories/Global/molecules/UtilityHeader.stories.tsx
- packages/storybook/src/stories/Global/organisms/ContentLayout.stories.tsx
- packages/ui-lib/src/Layouts/atoms/UtilityHeaderBack.tsx
- packages/ui-lib/src/Layouts/atoms/UtilityHeaderShare.tsx
- packages/ui-lib/src/Layouts/index.ts
- packages/ui-lib/src/Layouts/molecules/UtilityHeader.tsx
This iteration was made to allow the labels for the back and share buttons to be overridden. Whilst doing this and adding to the story I realised we quickly began to overload the props we were sending and things were getting messy. This becomes more problematic, the deeper that components are nested. For this reason I decided to refactor this early while it is only being used in one project and we can limit the impact of breaking changes.
The following props have been removed and will need to be changed: `backLink`, `showShareLink` and `shareLink`
They have been replaced with two new object props: `back` and `share` which contain everything that is needed.
Instead of `backLink`, use:
```
back = {
link: '/example',   // This replaces backLink
label: 'Back'       // Optional but intended …
```
> UtilityHeader label props and refactor

- package-lock.json
- package.json
- packages/ui-lib/package.json
**Features**
- **UtilityHeader:** Developers can now set custom labels for the back and share buttons.
The following props have been removed and need to be replaced:
- backLink
- showShareLink
- shareLink
These have been replaced with two new object props: back and share, as detailed below:
Back button configuration:
Replace backLink with the back object:
```ts
back = {  
link: '/example',   // Replaces backLink  
label: 'Back'       // Optional, useful for localization overrides  
}
```
Share button configuration:
Replace `shareLink` with the `share` object:
```ts
share = {  
link: true,              // Replaces shareLink  
label: 'Share'           // Optional, useful for localization overrides  
copiedLabel: 'Copied.'   // Shown after clicking, optional for localization overrides  
} …
```
> Bump for release 2.8.0

- packages/ui-lib/src/Form/atoms/Label.tsx
After the label refactor, the new required dot lost its spacing as reported here #531. It's been restored here:
Before:
After:
I checked various implementations of Label after doing this and noticed no regression or errors in things like Pagination. However, if these can be double checked it would be highly appreciated.
> Added rules for spacing require dot (Fixes #531)

- packages/example/src/pages/SplitLayout.tsx
- packages/storybook/src/stories/Global/organisms/NestedSplitLayout.stories.tsx
- packages/storybook/src/stories/Global/organisms/SplitLayout.stories.tsx
- packages/ui-lib/src/Layouts/index.ts
- packages/ui-lib/src/Layouts/molecules/SplitLayout.tsx
This PR is related to the request of [Enhance SplitLayout for better code integration related to open state](#538)
New `onSideAreaStateChange` for sideAreaState Changes:
A callback is now triggered every time the sideAreaState changes, allowing developers to monitor and respond to state transitions. 
New `defaultCollapsed` Prop added to sideArea prop:
A defaultCollapsed prop has been added to allow the side area to start in a collapsed state. This is particularly useful for scenarios where no stream data is available.
Behavior:
The defaultCollapse prop serves as an initial state only. If a localStorage variable for the side area exists (e.g., from previous interactions), its value takes precedence over defaultCollapse. As such, if the side area was last left open by the user, it will open …
> Add SideArea initial State and callbacks

- packages/ui-lib/src/Form/atoms/FilterOption.tsx
Fixes #535 using a one line CSS fix, so, a quick review (hopefully)!
After:
> Fixes #535 - Word wrap issue on jp labels

- packages/ui-lib/src/Layouts/molecules/UtilityHeader.tsx
- packages/ui-lib/src/Pages/atoms/PageTitle.tsx
Fixes issue #536 .
Previously the `$iconInGutter` was hardcoded so the `UtilityHeader` alignment didn't change on small breakpoints. This has been updated to be responsive but can be overridden by the props.
Before:
After:
> Responsive alignment of UtilityHeader

- package-lock.json
- package.json
- packages/ui-lib/package.json
**Release 2.8.3**
**Features**
- **UtilityHeader**: Updated the left alignment of the `Breadcrumbs` component on small devices. This behavior can be overridden by passing the `$iconInGutter` boolean prop.
**Fixes**
- **Filters:** Prevents text wrapping in labels when using Japanese. (Issue identified in filter options and buttons within `SortDropdown`)
> Bump for release 2.8.3

- package-lock.json
- package.json
- packages/ui-lib/package.json
Release 2.9.0
**Dependencies**
This release updates Storybook from version 6 to 8.
Storybook 8 requires `Node.js 18`. Updated instructions for running the project with Node 18 can be found in the [README](https://github.com/future-standard/scorer-ui-kit/blob/main/packages/ui-lib/README.md).
**Deprecated features and breaking changes**
The `JSX plugin` for Storybook has been removed in this version, as it is no longer supported by Storybook 8.
> Bump for release 2.9.0

- packages/ui-lib/src/Modals/ConfirmationModal.tsx
- packages/ui-lib/src/Modals/Modal.tsx
- packages/ui-lib/src/theme/legacy/styles.ts
- packages/ui-lib/src/theme/legacy/typography.ts
This PR addresses a request regarding the modal margin interfering with its vertical alignment.
- A conditional margin has been added when the isCloseEnable prop is set to false.
- Additionally, this PR includes a couple of small improvements:
- Fixed an issue where buttons in the confirmation modal were stacked instead of appearing in the same line.
- Replaced outdated theme variables with new style variables.
Storybook - Alerts -> Modals -> Basic
Before
After
**Storybook -> Alerts -> Modals -> Confirmation Template
Before**
**After**
> Margin Modal FIX

- packages/storybook/src/stories/Filters/molecules/DatePicker.stories.tsx
- packages/storybook/src/stories/Filters/organisms/FilterBar.stories.tsx
- packages/ui-lib/src/Filters/atoms/FilterDropHandler.tsx
- packages/ui-lib/src/Filters/molecules/DatePicker.tsx
- packages/ui-lib/src/Filters/molecules/DropdownDatePicker.tsx
- packages/ui-lib/src/Filters/organisms/FilterBar.tsx
- packages/ui-lib/src/helpers/index.tsx
Updated the DatePicker component to include "Apply" and "Cancel" buttons.
This update introduces the following new props to DatePicker:
```ts
cancelText = 'Cancel',
applyText = 'Apply',
hasApply = false,
onToggleCallback = () => { },
onCancelCallback = () => { },
onApplyCallback = () => { },
```
- This update is backward compatible for both `DatePicker` and `FilterBar`, meaning no changes are required unless DropdownDatePicker is used as a standalone component.
- `DatePicker` prop `hasApply` is false ensuring no UI changes for existing implementations.
- In `DropdownDatePicker`, `hasApply` defaults to true. To maintain the previous behavior, set `hasApply` to `false`. If the new behaviour is desired the developer needs to implement the `onCancelCallback` and `onApplyCallback` on their …
> Datepicker, cancel and apply buttons

- packages/storybook/src/stories/Form/Input/DurationSlider.stories.tsx
- packages/ui-lib/src/Form/molecules/DurationSlider.tsx
This feature request enhances the Slider Duration component by providing more flexible templating options for the right side title.
Related issue: [#212](https://github.com/future-standard/scorer-ui-kit/issues/212)
- This implementation maintains backward compatibility with the existing template.
- The new timeFormat prop allows developers to control the displayed format.
- One notable change is that the previous implementation automatically handled pluralization for hours, minutes, and seconds. If developers still require this, they will need to implement it manually on their side. They can refer to the logic in the [helpers index file](https://github.com/future-standard/scorer-ui-kit/blob/main/packages/ui-lib/src/helpers/index.tsx).
Review in Storybook Form -> Input -Duration Slider …
> Add Template String to Duration Slider

- .github/workflows/deploy.yml
- .github/workflows/lint.yml
Update of actions/cache to v4.0.2 because [actions/cache version prior v4 has been deprecated](https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down)
> Update github workflows to have v4 for actions/cache

- packages/storybook/src/stories/Filters/molecules/DatePicker.stories.tsx
- packages/storybook/src/stories/Filters/molecules/FilterInputs.stories.tsx
- packages/storybook/src/stories/helpers/datePicker_sample.ts
- packages/storybook/src/stories/helpers/sample_table_helpers.tsx
- packages/ui-lib/src/Filters/FilterTypes.ts
- packages/ui-lib/src/Filters/index.ts
- packages/ui-lib/src/Filters/molecules/DatePicker.tsx
- packages/ui-lib/src/Filters/molecules/DropdownDatePicker.tsx
- packages/ui-lib/src/Filters/molecules/FiltersResults.tsx
- packages/ui-lib/src/Filters/organisms/FilterBar.tsx
- packages/ui-lib/src/helpers/index.tsx
- packages/ui-lib/src/index.tsx
This PR contains two commits, which when reviewing I recommend you switch to review individually. This is because the first is moving the parts that caused the circular dependency issue, then the other renames the interfaces to match our naming convention in such cases. Viewing together just has a lot of noise as a result.
In response to #571, I was bothered by the fact it moved functions out of centralised places which goes against how we try to keep things scalable and reusable. Even though it was okay, it felt like bad practice that left some rough edges.
This fix moves `isDateInterval` out of `DatePicker.tsx` and in to `helpers`. It also moves the two interfaces it uses out of the same file to the `Filters/index.ts` file which is should be the central point for all the types and …
> Circular Dependency Fix (Manual Alternative)

- packages/storybook/src/stories/Form/Buttons/Button.stories.tsx
- packages/storybook/src/stories/Form/Buttons/ButtonWithIcons.stories.tsx
- packages/storybook/src/stories/Form/Buttons/ButtonWithLoading.stories.tsx
- packages/ui-lib/src/Form/atoms/Button.tsx
- packages/ui-lib/src/Form/atoms/ButtonWithIcon.tsx
- packages/ui-lib/src/Form/atoms/ButtonWithLoading.tsx
- packages/ui-lib/src/Form/index.ts
- packages/ui-lib/src/Icons/Icon.tsx
- packages/ui-lib/src/theme/ThemeHelpers.ts
- packages/ui-lib/src/theme/ThemeVariables.ts
- packages/ui-lib/src/theme/variables/Colors.ts
Update request for buttons:
Within the designs for improvements to filters, new button variations are now being used and need to be added to the UI Kit.
**The new theme options** are `Text Only` and `Outline`. These are mostly changes to the colours of the buttons and are all linked to the theme. `Text Only` implies there is no button although the clickable area is still the same with the optional icon still there although not it is expected to rarely be used.
The `Outline` variant also has a thicker outline than other buttons.
**For the xsmall button variant** change, the size of the icon has gone from `10` → `12` and the horizontal padding in the icon area has gone from `8` → `4`
No updates were made for any design differences for primary, secondary and warning buttons
The storybook …
> Button text-only outline

- packages/storybook/src/stories/Form/Switch.stories.tsx
This PR introduces improvements to the Switch Story in Storybook to allow better testing and visualization of both checked and defaultChecked props using knobs.
Previously, the checked prop was not clearly controlled via knobs, which made it difficult to simulate and test different states of the Switch component (checked, unchecked, and undefined). This change addresses that by adding a select knob for checked with three options: undefined, true (checked), and false (unchecked). The defaultChecked prop remains separately configurable via a boolean knob.
```
Introduced a new select knob for the checked prop with tri-state options:
"undefined" – to allow default behavior via defaultChecked
"true" – to force the switch to be in the checked state
"false" – to force the switch to be in the …
```
> Updating switch case knobs for storybook

- packages/storybook/src/stories/Filters/molecules/FilterDropdownExamples.stories.tsx
- packages/storybook/src/stories/Filters/molecules/FilterDropdownWithFooter.stories.tsx
- packages/ui-lib/src/Filters/atoms/FilterDropHandler.tsx
- packages/ui-lib/src/Filters/atoms/FilterDropdownContainer.tsx
- packages/ui-lib/src/Filters/atoms/FooterControls.tsx
- packages/ui-lib/src/Filters/molecules/DropdownDatePicker.tsx
- packages/ui-lib/src/Filters/molecules/FilterDropdown.tsx
- packages/ui-lib/src/Form/atoms/Button.tsx
- packages/ui-lib/src/Form/atoms/ButtonWithIcon.tsx
- packages/ui-lib/src/Form/index.ts
- packages/ui-lib/src/Icons/Icon.tsx
- packages/ui-lib/src/index.tsx
- packages/ui-lib/src/theme/variables/Colors.ts
Filter Dropdown Interaction Improvements. The update will include:
- Adding optional Submit, Cancel and Reset buttons to each dropdown as a standard.
- Considerations for custom components to easily use the same dropdown UI pattern. 
*Possibly this goes in to the DropdownContainer component.*
~Currently evaluating if onSelect property should become optional and callback be disabled if hasApply prop is provided.~
onSelect will act as onApply 
Will Follow up in a different PR with 
-> FilterBar correct integration and Storybook example
-> Integration of Footer controls with Datepicker
New `IWeight` interface for Icons weight. It was added for the ButtonWithIcon to have font-weight for text and icon. It does not cause a breaking change,  but maybe there is a suggestion for a more polish …
> Filter Dropdown Interaction Improvements
